Closes #57
thinknetica-django-lab-03/pvladimir1989 pull request #80
Opened 2021-06-25 21:25 UTC by pvladimir1989

7 5 sms
Closes #57

2021-06-25 22:02 UTC, mikhailborodin requested changes

2021-06-25 22:02 UTC, mikhailborodin commented on board/main/tasks.py
> +    if secret=
чего-то не хватает

2021-06-26 08:33 UTC, pvladimir1989 commented on board/main/tasks.py
> +    if secret=
Это не надо, случайно оставил

2021-06-26 22:03 UTC, mikhailborodin commented on board/main/tasks.py
> +    if secret=
а где сохраняется ответ от провайдера?

2021-06-27 17:54 UTC, pvladimir1989 commented on board/main/tasks.py
> +    if secret=
Вообще я возвращал ответ на консоль, а секретный ключ, который генерируется в SMSlog модели сохраняется в БД. Сейчас я добавил функционал, что при добавлении профиля нужно подтвердить секретный код из СМС, это доп верификация.

2021-06-28 08:06 UTC, mikhailborodin approved these changes

2021-06-28 09:44 UTC, merged