Closes #88
thinknetica-django-lab-03/pvladimir1989 pull request #95
Opened 2021-07-03 09:49 UTC by pvladimir1989

11.4 admin advanced
Closes #88

2021-07-03 21:51 UTC, mikhailborodin requested changes

2021-07-03 21:51 UTC, mikhailborodin commented on board/main/admin.py
> +    def make_archival(self, request, queryset):
данный Action можно было сделать сильно проще, например так `queryset.update(is_active=False)`

2021-07-05 08:35 UTC, pvladimir1989 commented on board/main/admin.py
> +    def make_archival(self, request, queryset):
Поправил

2021-07-05 12:12 UTC, mikhailborodin approved these changes

2021-07-05 13:47 UTC, merged