Closes #83
thinknetica-django-lab-03/pvladimir1989 pull request #96
Opened 2021-07-03 14:21 UTC by pvladimir1989

12.1 docker compose postgres
Closes #83

2021-07-03 21:53 UTC, mikhailborodin requested changes

2021-07-03 21:53 UTC, mikhailborodin commented on board/board/settings/settings.py
> +if 'sqlite3' == BACKEND_DB_ENGINE:
engine базы должен быть статичен и не зависеть от переменных окружения

2021-07-05 06:58 UTC, pvladimir1989 commented on board/board/settings/settings.py
> +if 'sqlite3' == BACKEND_DB_ENGINE:
Поправил

2021-07-05 20:31 UTC, mikhailborodin approved these changes

2021-07-06 08:35 UTC, merged